### PR TITLE
fix ad hoc filter replace bug

### LINKED ISSUE #167: ad-hocs are falsely applied to variables in query
Consider the following query:
```
topk_max($topk, max(sum(
    rate(vmalert_iteration_duration_seconds_sum{job=~"$job", instance=~"$instance", group=~"$group"}[$__rate_interval])
/
    rate(vmalert_iteration_duration_seconds_count{job=~"$job", instance=~"$instance", group=~"$group"}[$__rate_interval])
) by(job, instance, group)) 
by(job, group))
```
_taken from [playground](https://play-grafana.victoriametrics.com/d/LzldHAVnz_vm/victoriametrics-vmalert-vm?orgId=1&editPanel=23&var-ds=P38648FE0F8C5BEA2&var-job=All&var-instance=All&var-group=All&var-topk=5&var-adhoc=job%7C%3D%7Cmonitoring%2Fprometheus-benchmark-vmalert)._

Try applying the ad-hoc filter by `job` and see result. 

Expected behavior: filter is correctly applied to time series selectos
Actual behavior: filter gets applied to `$topk` variable:
```
    "error": "error when executing query=\"topk_max(5{job=\\\"monitoring/prometheus-benchmark-vmalert\\\"}, max(sum(\\n    rate(vmalert_iteration_duration_seconds_sum{job=~\\\"monitoring/prometheus-benchmark-vmalert\\\", instance=~\\\".*\\\", group=~\\\".*\\\", job=\\\"monitoring/prometheus-benchmark-vmalert\\\"}[60s])\\n/\\n    rate(vmalert_iteration_duration_seconds_count{job=~\\\"monitoring/prometheus-benchmark-vmalert\\\", instance=~\\\".*\\\", group=~\\\".*\\\", job=\\\"monitoring/prometheus-benchmark-vmalert\\\"}[60s])\\n) by(job, instance, group)) \\nby(job, group))\" on the time range (start=1718264865000, end=1718275665000, step=15000): argList: unexpected token \"{\"; want \",\", \")\"; unparsed data: \"{job=\\\"monitoring/prometheus-benchmark-vmalert\\\"}, max(sum(\\n    rate(vmalert_iteration_duration_seconds_sum{job=~\\\"monitoring/prometheus-benchmark-vmalert\\\", instance=~\\\".*\\\", group=~\\\".*\\\", job=\\\"monitoring/prometheus-benchmark-vmalert\\\"}[60s])\\n/\\n    rate(vmalert_iteration_duration_seconds_count{job=~\\\"monitoring/prometheus-benchmark-vmalert\\\", instance=~\\\".*\\\", group=~\\\".*\\\", job=\\\"monitoring/prometheus-benchmark-vmalert\\\"}[60s])\\n) by(job, instance, group)) \\nby(job, group))\""
```

### PR DESCRIPTION
**Pull request by yincongcyincong**
fix #167

### CODE REVIEW

**Comment by hagen1778** [comment]
@dmitryk-dk @Loori-R this looks like a nasty bug. Would appreciate your review and a set of tests to verify the change.

File: src/datasource.tsx [hunk 1]
```diff
@@ -1016,12 +1015,12 @@ export class PrometheusDatasource
     delete variables.__interval_ms;
 
     //Add ad hoc filters
-    const expr = this.enhanceExprWithAdHocFilters(target.expr);
+    const expr = this.templateSrv.replace(target.expr, variables, this.interpolateQueryExpr);
 
     return {
       ...target,
       legendFormat: this.templateSrv.replace(target.legendFormat, variables),
-      expr: this.templateSrv.replace(expr, variables, this.interpolateQueryExpr),
```
Comment (dmitryk-dk) [inline src/datasource.tsx:1024]: hi @yincongcyincong ! can you add the tests for your changes?

Comment (yincongcyincong) [reply src/datasource.tsx:1024]: ok , i will add

Comment (dmitryk-dk) [reply src/datasource.tsx:1024]: @yincongcyincong, it would be great if you could add a CHANGELOG description about the fix. Thank you!

Comment (hagen1778) [reply src/datasource.tsx:1024]: @dmitryk-dk I think we can add changelog line on our own if the follow-up commit, since @yincongcyincong might not have a context how we publish changes.

Comment (yincongcyincong) [reply src/datasource.tsx:1024]: i added the unit test, please check it.

**Review by hagen1778 — DISMISSED** [review]
LGTM

File: src/datasource.test.ts [hunk 2]
```diff
@@ -489,6 +506,26 @@ describe('PrometheusDatasource', () => {
...
+    it('AdhocFilters should not add filters', () => {
+      getAdhocFiltersMock.mockReturnValue([
+        {
+          key: 'k1',
+          operator: '=',
+          value: 'v1',
+        }
+      ]);
+      replaceMock.mockImplementation((str, params) => {
+        const topk = params['topk'] as ScopedVar;
```
Comment (dmitryk-dk) [inline src/datasource.test.ts:519]: Hi @yincongcyincong ! overall looks good! Please import `ScopedVars` from `@grafana/data;`

Comment (yincongcyincong) [reply src/datasource.test.ts:519]: ok

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Comment by dmitryk-dk** [comment]
@yincongcyincong, thank you for your contribution!
